config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do 
    member do 
      get   'caixa/abrir'
      post  'caixa/abrir', to: "caixa#abrirCaixa"
      get   'caixa/fechar'
      post  'caixa/fechar', to: "caixa#fecharCaixa"
    end
  end
  resources :vendas do
    resources :produto_vendas
    member do
      get :finalizarVenda
    end
  end
  resources :usuarios
  resources :logins
  get 'logins/index'
  get 'logins/destroy'
  resources :produtos do
    member do
      get :recebimento
      post :recebimento, to: "produtos#recebimentoAtualiza"
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/produto_venda.rb
class ProdutoVenda < ApplicationRecord
  belongs_to :produto
  belongs_to :venda
  validates :produto_id, presence: {message: 'deve ser preenchido.'}
  validates :qtd_produtos, numericality: true, presence: {message: 'deve ser preenchido.'}
end

app/controllers/produto_vendas_controller.rb
class ProdutoVendasController < ApplicationController
  before_action :get_venda
  before_action :set_produto_venda, only: [:show, :edit, :update, :destroy]

  # GET /produto_vendas
  # GET /produto_vendas.json
  def index
    @produto_vendas = @venda.produto_vendas
  end

  # GET /produto_vendas/1
  # GET /produto_vendas/1.json
  def show
  end

  # GET /produto_vendas/new
  def new
    @produto_venda = @venda.produto_vendas.build
    @todos_produtos = Produto.all
    @produtos = []
    @todos_produtos.each do |pp|
      nome = pp.nome
      id = pp.id
      @produtos.push([nome, id])
    end
  end

  # GET /produto_vendas/1/edit
  def edit
  end

  # POST /produto_vendas
  # POST /produto_vendas.json
  def create
    @mensagem = ""
    @produto_venda = @venda.produto_vendas.build(produto_venda_params)
    if @produto_venda.produto.qtd_estoque > 0
      if !@produto_venda.qtd_produtos.nil?
        if (@produto_venda.produto.qtd_estoque - @produto_venda.qtd_produtos) > 0
          respond_to do |format|
            if @produto_venda.save
              ProdutoVenda.update(@produto_venda.id, :valor => @produto_venda[:qtd_produtos].to_f * @produto_venda.produto.preco.to_f )
              Venda.update(@venda.id, :valor => @venda[:valor].to_f + (@produto_venda[:qtd_produtos].to_f * @produto_venda.produto.preco.to_f))
              format.html { redirect_to @venda, notice: 'Produto adicionado com sucesso.' }
              format.json { render :show, status: :created, location: @produto_venda }
            else
              format.html { render :new }
              format.json { render json: @produto_venda.errors, status: :unprocessable_entity }
            end
          end
        else
          redirect_to new_venda_produto_venda_path(@venda), notice: "Quantidade de produto excede a quantidade em estoque."
        end
      else
        redirect_to new_venda_produto_venda_path(@venda), notice: "Campo quantidade de produtos deve ser preenchido."
      end
    else
      redirect_to new_venda_produto_venda_path(@venda), notice: "Produto em falta no estoque."
    end
  end

  # PATCH/PUT /produto_vendas/1
  # PATCH/PUT /produto_vendas/1.json
  def update
    respond_to do |format|
      if @produto_venda.update(produto_venda_params)
        Venda.update(@venda.id, :valor => @venda[:valor].to_f - @produto_venda[:valor].to_f)
        ProdutoVenda.update(@produto_venda.id, :valor => @produto_venda[:qtd_produtos].to_f * @produto_venda.produto.preco.to_f )
        Venda.update(@venda.id, :valor => @venda[:valor].to_f + @produto_venda[:valor].to_f)
        format.html { redirect_to @venda, notice: 'Produto editado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto_venda }
      else
        format.html { render :edit }
        format.json { render json: @produto_venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produto_vendas/1
  # DELETE /produto_vendas/1.json
  def destroy
    @produto_venda.destroy
    Venda.update(@venda.id, :valor => @venda[:valor].to_f - @produto_venda[:valor].to_f)
    respond_to do |format|
      format.html { redirect_to @venda, notice: 'Produto removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto_venda
      @produto_venda = @venda.produto_vendas.where("id = ?", params[:id]).first
    end

    # Only allow a list of trusted parameters through.
    def produto_venda_params
      params.require(:produto_venda).permit(:produto_id, :venda_id, :qtd_produtos, :valor)
    end

  def get_venda
    @venda = Venda.find(params[:venda_id])
  end

end

app/helpers/produto_vendas_helper.rb
module ProdutoVendasHelper
end

app/views/produto_vendas/_form.html.erb
<p style="color: #cc0000" id="notice"><%= notice %></p>
<%= form_with(model: [@venda, produto_venda], local: true) do |form| %>
  <% if produto_venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto_venda.errors.count, "error") %> prohibited this produto_venda from being saved:</h2>

      <ul>
        <% produto_venda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-sm-4">
      <%= form.label :produto_id %>
      <%= form.select :produto_id, @produtos, {include: true}, class: "form-control"%>
    </div>

    <div class="col-sm-4">
      <%= form.label :qtd_produtos %>
      <%= form.text_field :qtd_produtos, class: "form-control" %>
    </div>
  </div>

  

  <div class="actions">
    <%= form.submit "Adicionar", class: "btn btn-success"%>
  </div>
<% end %>

app/views/produto_vendas/edit.html.erb
<h1>Editing Produto Venda</h1>

<%= render 'form', produto_venda: @produto_venda %>

<%= link_to 'Show', [@venda, @produto_venda] %> |
<%= link_to 'Back', venda_produto_vendas_path(@venda) %>

app/views/produto_vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produto Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Produto</th>
      <th>Venda</th>
      <th>Qtd produtos</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produto_vendas.each do |produto_venda| %>
      <tr>
        <td><%= produto_venda.produto_id %></td>
        <td><%= produto_venda.venda_id %></td>
        <td><%= produto_venda.qtd_produtos %></td>
        <td><%= produto_venda.valor %></td>
        <td><%= link_to 'Show venda', [@venda] %></td>
        <td><%= link_to 'Edit produto venda', edit_venda_produto_venda_path(@venda, produto_venda) %></td>
        <td><%= link_to 'Destroy produto venda',[@venda, produto_venda ], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto Venda', new_venda_produto_venda_path(@venda) %>

app/views/produto_vendas/new.html.erb
<h1>Adicionar produto a venda</h1>

<%= render 'form', produto_venda: @produto_venda %>

<%= link_to 'Voltar', venda_path(@venda) %>

app/views/produto_vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Produto:</strong>
  <%= @produto_venda.produto_id %>
</p>

<p>
  <strong>Venda:</strong>
  <%= @produto_venda.venda_id %>
</p>

<p>
  <strong>Qtd produtos:</strong>
  <%= @produto_venda.qtd_produtos %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto_venda.valor %>
</p>

<%= link_to 'Edit', edit_venda_produto_venda_path(@venda, @produto_venda) %> |
<%= link_to 'Back', venda_produto_vendas_path(@venda) %>