config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do 
    member do 
      get   'caixa/abrir'
      post  'caixa/abrir', to: "caixa#abrirCaixa"
      get   'caixa/fechar'
      post  'caixa/fechar', to: "caixa#fecharCaixa"
    end
  end
  resources :vendas do
    resources :produto_vendas
    member do
      get :finalizarVenda
    end
  end
  resources :usuarios
  resources :logins
  get 'logins/index'
  get 'logins/destroy'
  resources :produtos do
    member do
      get :recebimento
      post :recebimento, to: "produtos#recebimentoAtualiza"
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord
  attr_accessor
  validates :nome, presence: {message: "deve ser preenchido"}, uniqueness: true
  validates :categoria, presence: {message: "deve ser preenchido"}
  validates :qtd_estoque, presence: {message: "deve ser preenchido"}, numericality: true
  validates :preco, presence: {message: "deve ser preenchido"}, numericality: true

  has_many :produto_vendas
  has_many :vendas, through: :produto_vendas
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :logado

  def logado
    unless Usuario.checar_usuario_logado
      redirect_to logins_path
    end
  end

  # GET /produtos
  # GET /produtos.json
  def index
    if params[:nome]
      @produtos = Produto.where("nome like ?","%#{params[:nome]}%")
    else
      @produtos = Produto.all
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produtos_path, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update

    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produtos_path, notice: 'Produto editado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def recebimento
    @produto = Produto.find(params[:id])
  end

  def recebimentoAtualiza
    @produto = Produto.find(params[:id])
    if Produto.update(@produto.id, :qtd_estoque => @produto[:qtd_estoque].to_f + params[:recebimento].to_f)
      redirect_to produtos_path, notice: 'Recebimento de produto efetuado com sucesso.'
    else
      render recebimento_produto_path
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :categoria, :qtd_estoque, :preco)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-sm-4">
      <%= form.label :nome %>
      <%= form.text_field :nome, class: "form-control" %>
    </div>

    <div class="col-sm-4">
      <%= form.label :categoria %>
      <%= select('produto', :categoria, ['Bovino', 'Suino', 'caprino', 'Aves', 'Peixe'],{include:true}, {:class => 'form-control'}) %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-4">
      <%= form.label :qtd_estoque %>
      <%= form.text_field :qtd_estoque, class: "form-control" %>
    </div>

    <div class="col-sm-4">
      <%= form.label :preco %>
      <%= form.text_field :preco, :placeholder => "Por Kg.", class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12" style="margin-top: 10px; margin-bottom: 10px;">
      <%= form.submit "Salvar", class: 'btn btn-success'%>
    </div>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Visualizar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(produtos_path, :method =>:get) do %>
  <div class="row">
    <div class="col-sm-10">
      <%=text_field_tag('nome', nil, :placeholder => "Nome do produto", :class => "form-control") %>
    </div>
    <div class="col-sm-2">
      <%= submit_tag "buscar", class: "btn btn-secondary" %>
    </div>
  </div>
  
<% end %>
<br/>

<h1>Produtos</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Categoria</th>
      <th scope="col">Qtd estoque</th>
      <th scope="col">Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td scope="row"><%= produto.nome %></td>
        <td><%= produto.categoria %></td>
        <td><%= "%0.02f Kg" % produto.qtd_estoque %></td>
        <td><%= "R$ %0.02f" % produto.preco %></td>
        <td><%= link_to 'Visualizar', produto , id: "v-#{produto.nome}"%></td>
        <td><%= link_to 'Editar', edit_produto_path(produto), id: "e-#{produto.nome}" %></td>
        <td><%= link_to 'Deletar', produto, method: :delete, data: { confirm: 'Você deseja realmente excluir este produto?' } , id: "d-#{produto.nome}"%></td>
        <td><%= link_to 'Recebimento', recebimento_produto_path(produto), id: "r-#{produto.nome}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo produto', new_produto_path %>

app/views/produtos/new.html.erb
<div style="position: relative; top: 50px;">
    <h1>Novo produto</h1>

    <%= render 'form', produto: @produto%>

    <%= link_to 'Voltar', produtos_path %>
</div>

app/views/produtos/recebimento.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @produto.nome %></h2>

<%= form_with(url: recebimento_produto_path, method: :post, local: true, id: "form") do |form| %>
  <div style="position: relative;">
    <div class="row form-group">
      <div class="col-sm-6">
        <%= form.label "recebimento" %>
        <%= form.text_field "recebimento", id: "recebimento", class: "form-control"%>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-3">
        <button type="button" class="btn btn-success" onclick="validarDados()">Salvar</button>
        <%# <%= form.submit "Salvar", class: "btn btn-success" %>
      </div>
    </div>
 </div>

<script>
    function validarDados() {
      if (isNaN(document.getElementById('recebimento').value)) {
        alert("Preencha o campo recebimento com um número real")
      } else if (parseFloat(document.getElementById('recebimento').value) < 0) {
        alert("Preencha o campo com um número positivo");
      } else {
        var form = document.getElementById('form');
        form.submit();
      }
    }
</script>
<% end %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-4">
    <strong>Nome:</strong>
    <p>
      <%= @produto.nome %>
    </p>
  </div>
  <div class="col-sm-4">
    <strong>Categoria:</strong>
    <p>
      <%= @produto.categoria %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <strong>Qtd estoque:</strong>
    <p>
      <%= @produto.qtd_estoque %>
    </p>
  </div>
  <div class="col-sm-4">
    <strong>Preco:</strong>
    <p>
      <%= @produto.preco %>
    </p>
  </div>
</div>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>