config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do 
    member do 
      get   'caixa/abrir'
      post  'caixa/abrir', to: "caixa#abrirCaixa"
      get   'caixa/fechar'
      post  'caixa/fechar', to: "caixa#fecharCaixa"
    end
  end
  resources :vendas do
    resources :produto_vendas
    member do
      get :finalizarVenda
    end
  end
  resources :usuarios
  resources :logins
  get 'logins/index'
  get 'logins/destroy'
  resources :produtos do
    member do
      get :recebimento
      post :recebimento, to: "produtos#recebimentoAtualiza"
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/venda.rb
class Venda < ApplicationRecord
  has_many :produto_vendas
  has_many :produtos, through: :produto_vendas
  validates :valor, numericality: true, presence: {message: "deve ser preenchido."}
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]
  before_action :logado

  def logado
    unless Usuario.checar_usuario_logado
      redirect_to logins_path
    end
  end

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    caixa = Caixa.new
    unless caixa.algumCaixaAberto(Usuario.get_usuario.id)
      redirect_to root_url, notice: 'Nenhum caixa aberto, para efetuar uma venda abra o caixa.'
    else
      @venda = Venda.new
    end
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to @venda }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: 'Venda atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    for produto_venda in @venda.produto_vendas
      produto_venda.destroy
    end
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Venda cancelada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def finalizarVenda
    @venda = Venda.find(params[:id])

    caixa = Caixa.new
    caixa = caixa.getCaixaAberto (Usuario.get_usuario.id)
    caixa.valor_total = caixa.valor_total + @venda.valor 
    caixa.valor_arrecadado = caixa.valor_total - caixa.valor_inicial
    caixa.update({:valor_inicial => caixa.valor_inicial, :valor_total => caixa.valor_total, :valor_arrecadado => caixa.valor_arrecadado})

    @venda.produto_vendas.each do |produto_venda|
      Produto.update(produto_venda.produto_id, :qtd_estoque => produto_venda.produto.qtd_estoque - produto_venda[:qtd_produtos].to_f)
    end
    redirect_to root_path, notice: "Venda finalizada com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venda_params
      params.require(:venda).permit(:valor)
    end
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/vendas/_form.html.erb
<%= form_with(model: venda, local: true) do |form| %>
  <% if venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
        <% venda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor, value: "0" %>
  </div>

  <div class="actions">
    <%= form.submit "salvar", id: "clicar"%>
  </div>
<% end %>
<script>
    $('#clicar').trigger('click');
</script>

app/views/vendas/edit.html.erb
<h1>Editing Venda</h1>

<%= render 'form', venda: @venda %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.valor %></td>
        <td><%= link_to 'Show', venda %></td>
        <td><%= link_to 'Edit', edit_venda_path(venda) %></td>
        <td><%= link_to 'Destroy', venda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venda', new_venda_path %>

app/views/vendas/new.html.erb
<h1>New Venda</h1>

<%= render 'form', venda: @venda %>

<%= link_to 'Back', vendas_path %>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-12">
    <p>
      <strong>Valor Total:</strong>
      <% if @venda.valor == 0%>
        Nenhum produto adicionado
      <% else %>
        <%= "R$ %0.02f" % @venda.valor.round(2)%>
      <% end %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <h2>Produtos da venda</h2>
  </div>
</div>

<div class="row">
    <% for produto_venda in @venda.produto_vendas %>
      <div class="col-sm-3">
        <div class="card" style="width: 16rem; margin: 5px;">
          <div class="card-body">
            <h5 class="card-title"><%= produto_venda.produto.nome %></h5>
            <h6 class="card-subtitle mb-2 text-muted"></h6>
            <p class="card-text">
                <div class="row">
                  <div class="col-sm-12">
                    Quantidade: <%= "%0.02f Kg" % produto_venda.qtd_produtos %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    valor: <%= "R$ %0.02f" % produto_venda.valor %>
                  </div>
                </div>
            </p>
            <%= link_to 'Remover Produto',[@venda, produto_venda], method: :delete, data: { confirm: 'Deseja remover este produto da venda?' } %>
          </div>
        </div>
      </div>
    <% end %>
</div>

<div class="row" style="position: relative; top:20px;">
  <div class="col-sm-12">
    <%= link_to 'Cancelar Venda', @venda, method: :delete, data: { confirm: 'Deseja cancelar esta venda?' }, class: "btn btn-primary", :id => "cancelar"%>
    <%= link_to 'Adicionar Produto', new_venda_produto_venda_path(@venda), class: "btn btn-primary", :id => "addProduto" %>
    <%= link_to 'Finalizar Venda', finalizarVenda_venda_path(@venda), class: "btn btn-primary", :id => "finalizar" %>
  </div>
</div>