config/routes.rb
Rails.application.routes.draw do
  resources :usuarios do 
    member do 
      get   'caixa/abrir'
      post  'caixa/abrir', to: "caixa#abrirCaixa"
      get   'caixa/fechar'
      post  'caixa/fechar', to: "caixa#fecharCaixa"
    end
  end
  resources :vendas do
    resources :produto_vendas
    member do
      get :finalizarVenda
    end
  end
  resources :usuarios
  resources :logins
  get 'logins/index'
  get 'logins/destroy'
  resources :produtos do
    member do
      get :recebimento
      post :recebimento, to: "produtos#recebimentoAtualiza"
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frigorifico São José</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark navbar-light" style="background-color: #1d7de5;">
      <div class="container">
          <a class="navbar-brand" href="/">
            Frigorifico São José
          </a>
          <button class="navbar-toggler" type="button" style="border-color:white;" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse " id="navbarNav">
          <%if Usuario.checar_usuario_logado ==  false%>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Login', logins_path, class: "nav-link", style: "color: white;"%>
              </li>
              <li class="nav-item">
                <%= link_to 'Cadastre-se', new_usuario_path, class: "nav-link", style: "color: white;" %>
              </li>
            </ul>
          <%else %>
            <% @usuario = Usuario.get_usuario %>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Produtos', produtos_path, class: "nav-link", style: "color: white;" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Vendas', new_venda_path, class: "nav-link", id: "vendas", style: "color: white;" %>
              </li>
              <li class="nav-item">
                <%= link_to "Abrir caixa", caixa_abrir_usuario_url(@usuario.id), id: "abrir-caixa", class: "nav-link", style: "color: white;" %>
              </li>
              <li class="nav-item">
                <%= link_to "Fechar caixa",  caixa_fechar_usuario_url(@usuario.id), id: "fechar-caixa", class: "nav-link", style: "color: white;" %>
              </li>
              <li class="nav-item">
                <%= link_to "#{@usuario.login}", "/usuarios/#{@usuario.id}", class: "nav-link", style: "color: white;" %>
              </li>

              <li class="nav-item">
                <%= link_to 'Sair', logins_destroy_path, method: :delete, class: "nav-link", style: "color: white;" %>
              </li>
            </ul>
          <%end %>
        </div>
      </div>
    </nav>
    <div class="container"> 
      <%= yield %>
    </div>
   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        $('#visualizar_senha').click(function(){
          var pw = document.getElementById("password").type;
          if (pw == "password") {
            document.getElementById("password").type = "text";
          } else {
            document.getElementById("password").type = "password"
          }
        })
      })
    </script>
  </body>
</html>